<!DOCTYPE html>
<html lang="en">
<head>
  <title>PHP Paginator Demo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
 
    <!--  Material I cons from Google Fonts. -->
   <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
   
   <link rel="stylesheet" href="public/paginator.css">
</head>
<body>
  
<div class="container" style="text-align:center">
  <h1>My First Material Design Page</h1>
  <p>This is some text.</p>
  <?php
	$otpPageNav = \OSOLUtils\Helpers\PHPPaginator::getInstance();
	$sql = "SELECT * FROM otp_sample_list";
	$recordsOfPage = $otpPageNav->fetch_records($sql);//returns the records as an array
	
	
	$pageNav = $otpPageNav->page_nav."<br />";//displays like 1,2,3,4
	$recNums =  $otpPageNav->display_rec_nums."<br />";//displays like 1 to 10 of 25							
	$fpnl =  $otpPageNav->fpnlLinks."<br />";//displays like << < > >>
	$links2Display = $pageNav . $recNums . $fpnl;
	
	
	echo $links2Display;
	
	
	$colNum = 0;
	$rowNum = 0;
	$itemNo =0;
	foreach($recordsOfPage as $recordOfPage)
	{
		$itemNo = $recordOfPage['id'];
		$i =  $itemNo - 1;
		$modulus = floor($i/8);// gives the row no
		$remainder = $i%8;// gives column no
		$rowNum = $modulus  * -118;
		$colNum = $remainder * -75;
		
		$bgX =  $colNum ;
		$bgY =  $rowNum ;
		
	?>
	<div class="osol-paginator-row">
		<div class="osol-paginator-left-column osol-paginator-thumbnail-container"><?php echo $itemNo;?></div>
		<div class="osol-paginator-thumbnail-bg osol-paginator-thumbnail-container " style="background-position: <?php echo $bgX;?>px <?php echo $bgY;?>px;"></div>
		<div class="osol-paginator-right-column center">
			<p>
				i = <?php echo $i;?>,<br />i%8 = <?php echo $i%8;?>,bgX = <?php echo $bgX;?>, bgY = <?php echo $bgY;?><br />
				<?php echo $recordOfPage['sample_text'];?>
			</p>
		</div>
	</div>
	<?php
	}//foreach($recordsOfPage as $recordOfPage)
	
	
	echo $links2Display;
	
	
	?>
</div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  
</body>
</html> 