<!DOCTYPE html>
<html lang="en">
<head>
  <title>Material Design Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
 
    <!--  Material I cons from Google Fonts. -->
   <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
   
   <link rel="stylesheet" href="public/paginator.css">
</head>
<body>
  
<div class="container">
  <h1>My First Material Design Page</h1>
  <p>This is some text.</p>
  <?php
	$colNum = 0;
	$rowNum = 0;
	$itemNo =0;
	$sqls = array();
	$sqls[] = "DROP TABLE IF EXISTS `otp_sample_list`;";
	$sqls[] = "CREATE TABLE IF NOT EXISTS `otp_sample_list` (
			  `id` bigint(20) NOT NULL AUTO_INCREMENT,
			  `sample_text` varchar(255) NOT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
	for($i = 0 ; $i < 32 ; $i++)
	{
		
		
		$bgX =  $colNum ;
		$bgY =  $rowNum ;
		$itemNo++;
		$sqls[] = "INSERT INTO `otp_sample_list` (`sample_text`) VALUES('This is row {$itemNo}');";
		if($i%8 == 7)
		{
			$rowNum -= 118;
			$colNum = 0;
		}
		else
		{
			$colNum -= 75;
		}//if($i%8 == 7)
		
		
	?>
	<div class="osol-paginator-row">
		<div class="osol-paginator-left-column osol-paginator-thumbnail-container"><?php echo $itemNo;?></div>
		<div class="osol-paginator-thumbnail-bg osol-paginator-thumbnail-container " style="background-position: <?php echo $bgX;?>px <?php echo $bgY;?>px;"></div>
		<div class="osol-paginator-right-column center">
			<p>
				<?php echo $i;?>,<br /><?php echo $i%8;?>,<?php echo $bgX;?>, <?php echo $bgY;?>
			</p>
		</div>
	</div>
	<?php
	}//for(var $i = 0 ; $i < 20 ; $i++)
	echo "<pre>".join("\r\n",$sqls)."</pre>";
	?>
</div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  
</body>
</html> 